### ISSUE TITLE
Add support for python version

### ISSUE THREAD

**Issue by bbaassssiiee** [evandam/evandam.conda#11]
Yes, it is late, but we still need to be able to switch between python3 and back to python2.

https://docs.anaconda.com/anaconda/user-guide/tasks/switch-environment/

conda create -y --name py27 python=2.7
conda create -y --name py36 python=3.6
conda create -y --name py37 python=3.7

**Comment by evandam** [comment]
Can you explain a bit what you mean by this? It should be possible to create environments with different python versions:
```yml
- conda:
    name: python=2.7
    environment: py27
```
