### ISSUE TITLE
[Errno 22] Invalid argument when configuring conda python3 environments

### ISSUE THREAD

**Issue by bbaassssiiee** [evandam/evandam.conda#17]
In my playbook for packer I try:
```
  tasks:
    - name: Create conda environments
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        name: "python={{ item.python }}"
        environment: "{{ item.pyenv }}"
      with_items: "{{ miniconda_envs }}"

    - name: Configure conda environments
      conda:
        executable: "{{ miniconda_dir }}/bin/conda"
        environment: "{{ item.pyenv }}"
        channels: "{{ miniconda_channels }}"
        name: "{{ miniconda_packages }}"
        state: present
      with_items: "{{ miniconda_envs }}"
```
This fails with:
```
TASK [Configure conda environments] ********************************************
Monday 25 November 2019  15:50:45 -0500 (0:00:47.290)       0:14:10.788 *******
changed: [127.0.0.1] => (item={u'python': u'2.7', u'pyenv': u'/opt/conda/envs/py27_64'})
failed: [127.0.0.1] (item={u'python': u'3.6', u'pyenv': u'/opt/conda/envs/py36_64'}) => changed=false 
  cmd: /opt/conda/bin/conda list --json --prefix /opt/conda/envs/py36_64
  item:
    pyenv: /opt/conda/envs/py36_64
    python: '3.6'
  msg: '[Errno 22] Invalid argument'
  rc: 22
failed: [127.0.0.1] (item={u'python': u'3.7', u'pyenv': u'/opt/conda/envs/py37_64'}) => ged=false 
  cmd: /opt/conda/bin/conda list --json --prefix /opt/conda/envs/py37_64
  item:
    pyenv: /opt/conda/envs/py37_64
    python: '3.7'
  msg: '[Errno 22] Invalid argument'
  rc: 22
```
