### ISSUE TITLE
Python 3.10 fails

### ISSUE THREAD

**Issue by eelcovv** [evandam/evandam.conda#28]
Installing python 3.10 fails as it is seen as 3.1. My task looks like:
```

- name: Create a conda environment
  conda:
    name: python
    version: 3.10
    environment: py310
    executable: "{{ mamba_prefix }}/bin/mamba"
    state: present
```
give the warning:

```
[WARNING]: The value "3.1" (type float) was converted to "'3.1'" (type string). If this does not look like what you expect, quote the
entire value to ensure it does not change.
```

Apparently 3.10 is converted to 3.1 and that version is unknown and it fails after thta. 

If I put quotes around 3.10 like "3.10"   then it works, however, the version is not read and just python 3.9 is installed. 

Any idea how to fix this?
